name: flame_game_jam_2025
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flame: 1.28.1
  flame_tiled: 3.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: 1.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  shaders:
    - assets/shaders/hyperspace-streaks.frag
    - assets/shaders/hyperspace-tunnel.frag
    - assets/shaders/star-nest.frag
